In [14]:
import numpy as np
arr = np.ones((3,4), dtype=np.float64)
arr.strides

(32, 8)

In [15]:
e = np.empty((2,3), dtype=np.float64)
print(e.shape)

(2, 3)


In [21]:
z = np.zeros((2,3), dtype=np.int32)
print(z)

[[0 0 0]
 [0 0 0]]


In [20]:
e.fill(0)
zl = np.zeros_like(e)
print(zl)

[[0. 0. 0.]
 [0. 0. 0.]]


In [48]:
np.issubdtype(np.int64, np.integer)
np.issubdtype(np.bool_, np.generic)

True

In [25]:
a = np.arange(1,7)
b = a.reshape((2, -1))
print(b)

[[1 2 3]
 [4 5 6]]


In [26]:
v = b.ravel()
v[0] = 99
print(b[0,0])

99


In [27]:
c = b.flatten()
c[0] = 0
print(b[0,0])

99


In [29]:
c_arr = np.ones((2,3), order='C')
c_arr.strides
c_arr.flags['C_CONTIGUOUS']

True

In [30]:
c_arr = np.ones((2,3), order='F')
c_arr.strides
c_arr.flags['F_CONTIGUOUS']

True

In [12]:
import numpy as np
arr = np.array([1,2])
np.repeat(arr, 3)

array([1, 1, 1, 2, 2, 2])

In [31]:
arr = np.array([1, 2])
np.tile(arr, 3)

array([1, 2, 1, 2, 1, 2])

In [32]:
arr = np.array([10,20,30,40])
arr.take([0,3])

array([10, 40])

In [33]:
arr = np.zeros(4)
arr.put([1,2], [7,9])

In [35]:
a = np.ones((4,3))
b = np.array([1,2,3])
(a+b).shape

(4, 3)

In [36]:
x = np.arange(4)[:, np.newaxis]
(x+b).shape

(4, 3)

In [ ]:
v = np.broadcast_to(4,3)
v.strides

(0,)

In [40]:
arr = np.arange(1,5)
np.add.reduce(arr)

np.int64(10)

In [41]:
arr = np.arange(1,5)
np.add.accumulate(arr)

array([ 1,  3,  6, 10])

In [43]:
x = np.array([1,2,3])
np.multiply.outer(x,x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [44]:
arr = np.arange(8)
np.add.reduceat(arr, [0,4])

array([ 6, 22])

In [ ]:
def scalar_add(x, y):
    return x + y
my_add = np.frompyfunc(scalar_add, 2, 1)
result = my_add([1, 2], [3, 4])

print(result)

from numba import vectorize, float64
@vectorize([float64(float64, float64)], target='parallel')
def fast_add(x, y):
    return x + y

[4 6]
